### ISSUE TITLE
[Public_key.verify]'s ECDSA evaluation mishandles long digests

### ISSUE THREAD

**Issue by torinnd** [mirleft/ocaml-x509#158] opened 2022-09-08 10:55 UTC
_(caveat emptor: I am not a cryptographer. I just read a wikipedia article)_

There's a deviation in behavior between ocaml-x509 and other tools that verify x509 certificates, like OpenSSL or Chrome. Specifically, ocaml-x509 doesn't properly evaluate public key verification iff the hash function produces a digest longer than the length of the group order. I've observed an issue with a P-256 key (group order length '32') used with ECDSA_SHA384 (hash function digest length '48') around this code:

https://github.com/mirleft/ocaml-x509/blob/e87d4baef3faedc05e1e4f2e36e16a4def5894ff/lib/public_key.ml#L140-L147

[d] ends up being 48 bytes long when passed to [P256.Dsa.verify], which causes the function to silently fail with a [Message_too_long] exception. This is expected / correct / documented in the MLI:

https://github.com/mirage/mirage-crypto/blob/e60bbcbd5d3e0aebe4aadd2663e6cec6c3f9a38e/ec/mirage_crypto_ec.mli#L115-L119
`  val verify : key:pub -> Cstruct.t * Cstruct.t -> Cstruct.t -> bool
  (** [verify ~key (r, s) digest] verifies the signature [r, s] on the message
      [digest] with the public [key]. The return value is [true] if verification
      was successful, [false] otherwise. If the message has more bits than the
      group order, the result is false. *)`

From [wikipedia](https://en.wikipedia.org/wiki/Elliptic_Curve_Digital_Signature_Algorithm#Signature_verification_algorithm):

> After that, Bob follows these steps:
> 
> 1. Verify that r and s are integers in [1,n-1]. If not, the signature is invalid.
> 2. Calculate e={HASH}(m), where HASH is the same function used in the signature generation.
> 3. Let z be the L_{n} leftmost bits of e.

I think Step 3 is missed here. I fixed this in a test environment by applying [Cstruct.take ~max:32] to [d] before passing it to the verify function [P256.Dsa.verify]. That should probably be baked into the logic for all four [key] cases, with [max] set to the appropriate [byte_length] (e.g. https://github.com/mirage/mirage-crypto/blob/e60bbcbd5d3e0aebe4aadd2663e6cec6c3f9a38e/ec/mirage_crypto_ec.ml#L738).

I'll offer the extra context that this isn't generally considered a best practice by (at least) Mozilla. See [Section 5.1.2 of their policy](https://www.mozilla.org/en-US/about/governance/policies/security-group/certs/policy/#5-certificates) where they claim that P-384 should be used with ECDSA_SHA384 to avoid these length mismatch issues. However, it is technically allowed (rather, not disallowed) by the [Baseline Requirements (Section 6.1.5)](https://cabforum.org/wp-content/uploads/CA-Browser-Forum-BR-1.8.4.pdf) various Certificate Authorities agree upon and should probably be supported by x509 libraries like ocaml-x509.

This truncation step is also a requirement when signing. I haven't verified this myself, but having spot checked the implementation of [Private_key.sign], it may be the case that this bug exists there as well.

**Comment by hannesm** [comment] 2022-09-08 11:53
Oh, thanks for opening the issue. I'm travelling and will be back next week. If I understand you correctly, this is best be fixed in mirage-crypto-ec (since it affects any ECDSA signature)? Do you have any test vector for this?

**Comment by torinnd** [comment] 2022-09-08 12:11
[verify]'s interface implies to me that it is up to callers to ensure their [digest] is appropriately sized. If that's the case I think ocaml-x509 should be handling the truncation (though mirage-crypto-ec has the relevant [byte_length] information, which might need to be exposed to avoid code duplication / drift). I suppose one could change the behavior of [verify] to silently handle the truncation instead of failing, but am uncertain about the safety of doing so.

I don't have the arcana involved in convincing OpenSSL to mint such a certificate chain available. I'll try to sort that out and bump this issue with the test case, if you don't get to it first.

**Comment by hannesm** [comment] 2022-09-13 10:57
I indeed have a regression test in my ecdsa-long-digest branch, https://github.com/hannesm/ocaml-x509/commit/396d67c2168510b73c90a90203246719fb48e9e7

**Comment by hannesm** [comment] 2022-09-13 10:59
FWIW to generate a P256 key: `openssl ecparam -out server.key -name secp256r1 -genkey`
to generate a CA certificate using this key: `openssl req -new -x509 -key server.key -out server.pem -days 360 -sha384 -addext keyUsage=keyCertSign`

**Comment by hannesm** [comment] 2022-09-13 11:30
progress: https://github.com/mirage/mirage-crypto/pull/164/commits/844b0598562f3716f428b37f9bcee14dfd69733f adds byte_length to the Dsa module type in Mirage_crypto_ec.

**Comment by hannesm** [comment] 2022-09-14 11:32
see #159 for a test and fix. does this work for you?

**Comment by torinnd** [comment] 2022-09-14 11:40
I am not familiar enough with [Cstruct] to opine on the correctness of [Cstruct.sub] vs [Cstruct.take]. Naively I might've assumed it was always safe to call [Cstruct.take], but I expect this is semantically the same thing!

**Comment by hannesm** [comment] 2022-09-14 11:44
`Cstruct.take` is pretty new, and I have not used it anywhere ;) That's my reasoning for using Cstruct.sub (which has been around since ever) ;)

**Comment by torinnd** [comment] 2022-09-14 11:51
Oh, that only addresses the verify step. Did you look at whether signing works as well?

**Comment by hannesm** [comment] 2022-09-14 11:55
in `Private_key.sign`, the `Public_key.trunc` is applied as well before the `Dsa.sign` is called (part of 793b1660c14294788f9a65bdbe672a49b28fca03). So the code you refer to is now different :)

But indeed I have not written a test for this.

**Closed** 2022-09-14 14:28 UTC

**Comment by hannesm** [comment] 2022-09-14 14:36
I manually tested `sign` with a modified ocaml-certify and openssl locally, merged the PR and cut a release. Thanks again for opening this issue.
